version: "3"
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: laravel
    working_dir: /app
    volumes:
      - ./src:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    depends_on:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./src:/app

  redis:
    container_name: redis
    image: "redis:alpine"

  beanstalk:
    container_name: beanstalk
    image: "jonbaldie/beanstalkd"

  queue:
    image: vivifyideas/php-fpm-production-docker-alpine:7.4
    container_name: queue
    working_dir: /app
    command: 'php artisan queue:listen --tries=3 --timeout=60'
    volumes:
      - ./src:/app

  db:
    image: mariadb:10.2
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  mailhog:
    image: "mailhog/mailhog"
    container_name: mailhog
    ports:
      - 8025:8025

volumes:
  db:

