name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CD
        run: |
          sh -c "cd ./src"

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions

#      - name: Install dependencies
#        working-directory: ./src
#        run: |
#          sh -c "composer install --no-scripts --no-progress"
#
#      - name: Run psalm
#        working-directory: ./src
#        run: |
#          sh -c "/composer/vendor/bin/psalm  --output-format=github $*"